/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.9/samples
 */

plugins {
    kotlin("jvm") version "2.0.0"
    application
}

repositories {
    mavenCentral()
}

dependencies {
    // https://github.com/grpc/grpc-java/blob/master/README.md
    // Suggested as runtime only, but I struggled to get ManagedChannelBuilder to use SSL correctly, netty just works.
    implementation("io.grpc:grpc-netty-shaded:1.65.0")
    // Java 9+ needs this
    compileOnly("org.apache.tomcat:annotations-api:6.0.53")

    // Kotlin
    implementation(kotlin("stdlib"))
    implementation("io.grpc:grpc-kotlin-stub:1.4.1")
    implementation("io.grpc:grpc-protobuf:1.65.1")
    implementation("io.grpc:grpc-stub:1.65.1")
    implementation("com.google.protobuf:protobuf-kotlin:4.27.3")
    implementation("com.google.protobuf:protobuf-java:4.27.3")

    // Async stuff
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.8.1")
    // JWT stuff
    implementation("io.github.cdimascio:dotenv-kotlin:6.3.1")
    // Kotlin test
    testImplementation(kotlin("test"))

}

application {
    mainClass.set("MainKt")
}

tasks.withType<org.jetbrains.kotlin.gradle.tasks.KotlinCompile> {
    compilerOptions {
        jvmTarget.set(org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_21)
    }
}

java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(21))
    }
}

sourceSets {
    main {
        kotlin {
            srcDir("../protobuf/kotlin")
        }
        java {
            srcDir("../protobuf/java")
        }
    }
}
