// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.27.1
// source: jokes-on-the-go/jokeserver.proto

package jokes_on_the_go

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// JokesClient is the client API for Jokes service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type JokesClient interface {
	// Ensures the service is up. Just for testing
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
}

type jokesClient struct {
	cc grpc.ClientConnInterface
}

func NewJokesClient(cc grpc.ClientConnInterface) JokesClient {
	return &jokesClient{cc}
}

func (c *jokesClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, "/jokeserver.Jokes/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// JokesServer is the server API for Jokes service.
// All implementations must embed UnimplementedJokesServer
// for forward compatibility
type JokesServer interface {
	// Ensures the service is up. Just for testing
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	mustEmbedUnimplementedJokesServer()
}

// UnimplementedJokesServer must be embedded to have forward compatible implementations.
type UnimplementedJokesServer struct {
}

func (UnimplementedJokesServer) Ping(context.Context, *PingRequest) (*PingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedJokesServer) mustEmbedUnimplementedJokesServer() {}

// UnsafeJokesServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to JokesServer will
// result in compilation errors.
type UnsafeJokesServer interface {
	mustEmbedUnimplementedJokesServer()
}

func RegisterJokesServer(s grpc.ServiceRegistrar, srv JokesServer) {
	s.RegisterService(&Jokes_ServiceDesc, srv)
}

func _Jokes_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JokesServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/jokeserver.Jokes/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JokesServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Jokes_ServiceDesc is the grpc.ServiceDesc for Jokes service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Jokes_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "jokeserver.Jokes",
	HandlerType: (*JokesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _Jokes_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "jokes-on-the-go/jokeserver.proto",
}
