// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: protobuf/jokeserver.proto
// Protobuf Java Version: 4.27.1

package sb.jokesonthego.jokeservice;

/**
 * Protobuf type {@code jokeserver.GetAnyRandomJokeResponse}
 */
public final class GetAnyRandomJokeResponse extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:jokeserver.GetAnyRandomJokeResponse)
    GetAnyRandomJokeResponseOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 1,
      /* suffix= */ "",
      GetAnyRandomJokeResponse.class.getName());
  }
  // Use GetAnyRandomJokeResponse.newBuilder() to construct.
  private GetAnyRandomJokeResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private GetAnyRandomJokeResponse() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return sb.jokesonthego.jokeservice.JokeServerProto.internal_static_jokeserver_GetAnyRandomJokeResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return sb.jokesonthego.jokeservice.JokeServerProto.internal_static_jokeserver_GetAnyRandomJokeResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            sb.jokesonthego.jokeservice.GetAnyRandomJokeResponse.class, sb.jokesonthego.jokeservice.GetAnyRandomJokeResponse.Builder.class);
  }

  private int bitField0_;
  public static final int JOKE_FIELD_NUMBER = 1;
  private sb.jokesonthego.jokeservice.Joke joke_;
  /**
   * <code>.jokeserver.Joke joke = 1;</code>
   * @return Whether the joke field is set.
   */
  @java.lang.Override
  public boolean hasJoke() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.jokeserver.Joke joke = 1;</code>
   * @return The joke.
   */
  @java.lang.Override
  public sb.jokesonthego.jokeservice.Joke getJoke() {
    return joke_ == null ? sb.jokesonthego.jokeservice.Joke.getDefaultInstance() : joke_;
  }
  /**
   * <code>.jokeserver.Joke joke = 1;</code>
   */
  @java.lang.Override
  public sb.jokesonthego.jokeservice.JokeOrBuilder getJokeOrBuilder() {
    return joke_ == null ? sb.jokesonthego.jokeservice.Joke.getDefaultInstance() : joke_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getJoke());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getJoke());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof sb.jokesonthego.jokeservice.GetAnyRandomJokeResponse)) {
      return super.equals(obj);
    }
    sb.jokesonthego.jokeservice.GetAnyRandomJokeResponse other = (sb.jokesonthego.jokeservice.GetAnyRandomJokeResponse) obj;

    if (hasJoke() != other.hasJoke()) return false;
    if (hasJoke()) {
      if (!getJoke()
          .equals(other.getJoke())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasJoke()) {
      hash = (37 * hash) + JOKE_FIELD_NUMBER;
      hash = (53 * hash) + getJoke().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static sb.jokesonthego.jokeservice.GetAnyRandomJokeResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static sb.jokesonthego.jokeservice.GetAnyRandomJokeResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static sb.jokesonthego.jokeservice.GetAnyRandomJokeResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static sb.jokesonthego.jokeservice.GetAnyRandomJokeResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static sb.jokesonthego.jokeservice.GetAnyRandomJokeResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static sb.jokesonthego.jokeservice.GetAnyRandomJokeResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static sb.jokesonthego.jokeservice.GetAnyRandomJokeResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static sb.jokesonthego.jokeservice.GetAnyRandomJokeResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static sb.jokesonthego.jokeservice.GetAnyRandomJokeResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static sb.jokesonthego.jokeservice.GetAnyRandomJokeResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static sb.jokesonthego.jokeservice.GetAnyRandomJokeResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static sb.jokesonthego.jokeservice.GetAnyRandomJokeResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(sb.jokesonthego.jokeservice.GetAnyRandomJokeResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code jokeserver.GetAnyRandomJokeResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:jokeserver.GetAnyRandomJokeResponse)
      sb.jokesonthego.jokeservice.GetAnyRandomJokeResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return sb.jokesonthego.jokeservice.JokeServerProto.internal_static_jokeserver_GetAnyRandomJokeResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return sb.jokesonthego.jokeservice.JokeServerProto.internal_static_jokeserver_GetAnyRandomJokeResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              sb.jokesonthego.jokeservice.GetAnyRandomJokeResponse.class, sb.jokesonthego.jokeservice.GetAnyRandomJokeResponse.Builder.class);
    }

    // Construct using sb.jokesonthego.jokeservice.GetAnyRandomJokeResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        getJokeFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      joke_ = null;
      if (jokeBuilder_ != null) {
        jokeBuilder_.dispose();
        jokeBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return sb.jokesonthego.jokeservice.JokeServerProto.internal_static_jokeserver_GetAnyRandomJokeResponse_descriptor;
    }

    @java.lang.Override
    public sb.jokesonthego.jokeservice.GetAnyRandomJokeResponse getDefaultInstanceForType() {
      return sb.jokesonthego.jokeservice.GetAnyRandomJokeResponse.getDefaultInstance();
    }

    @java.lang.Override
    public sb.jokesonthego.jokeservice.GetAnyRandomJokeResponse build() {
      sb.jokesonthego.jokeservice.GetAnyRandomJokeResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public sb.jokesonthego.jokeservice.GetAnyRandomJokeResponse buildPartial() {
      sb.jokesonthego.jokeservice.GetAnyRandomJokeResponse result = new sb.jokesonthego.jokeservice.GetAnyRandomJokeResponse(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(sb.jokesonthego.jokeservice.GetAnyRandomJokeResponse result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.joke_ = jokeBuilder_ == null
            ? joke_
            : jokeBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof sb.jokesonthego.jokeservice.GetAnyRandomJokeResponse) {
        return mergeFrom((sb.jokesonthego.jokeservice.GetAnyRandomJokeResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(sb.jokesonthego.jokeservice.GetAnyRandomJokeResponse other) {
      if (other == sb.jokesonthego.jokeservice.GetAnyRandomJokeResponse.getDefaultInstance()) return this;
      if (other.hasJoke()) {
        mergeJoke(other.getJoke());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getJokeFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private sb.jokesonthego.jokeservice.Joke joke_;
    private com.google.protobuf.SingleFieldBuilder<
        sb.jokesonthego.jokeservice.Joke, sb.jokesonthego.jokeservice.Joke.Builder, sb.jokesonthego.jokeservice.JokeOrBuilder> jokeBuilder_;
    /**
     * <code>.jokeserver.Joke joke = 1;</code>
     * @return Whether the joke field is set.
     */
    public boolean hasJoke() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.jokeserver.Joke joke = 1;</code>
     * @return The joke.
     */
    public sb.jokesonthego.jokeservice.Joke getJoke() {
      if (jokeBuilder_ == null) {
        return joke_ == null ? sb.jokesonthego.jokeservice.Joke.getDefaultInstance() : joke_;
      } else {
        return jokeBuilder_.getMessage();
      }
    }
    /**
     * <code>.jokeserver.Joke joke = 1;</code>
     */
    public Builder setJoke(sb.jokesonthego.jokeservice.Joke value) {
      if (jokeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        joke_ = value;
      } else {
        jokeBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.jokeserver.Joke joke = 1;</code>
     */
    public Builder setJoke(
        sb.jokesonthego.jokeservice.Joke.Builder builderForValue) {
      if (jokeBuilder_ == null) {
        joke_ = builderForValue.build();
      } else {
        jokeBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.jokeserver.Joke joke = 1;</code>
     */
    public Builder mergeJoke(sb.jokesonthego.jokeservice.Joke value) {
      if (jokeBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          joke_ != null &&
          joke_ != sb.jokesonthego.jokeservice.Joke.getDefaultInstance()) {
          getJokeBuilder().mergeFrom(value);
        } else {
          joke_ = value;
        }
      } else {
        jokeBuilder_.mergeFrom(value);
      }
      if (joke_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.jokeserver.Joke joke = 1;</code>
     */
    public Builder clearJoke() {
      bitField0_ = (bitField0_ & ~0x00000001);
      joke_ = null;
      if (jokeBuilder_ != null) {
        jokeBuilder_.dispose();
        jokeBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.jokeserver.Joke joke = 1;</code>
     */
    public sb.jokesonthego.jokeservice.Joke.Builder getJokeBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getJokeFieldBuilder().getBuilder();
    }
    /**
     * <code>.jokeserver.Joke joke = 1;</code>
     */
    public sb.jokesonthego.jokeservice.JokeOrBuilder getJokeOrBuilder() {
      if (jokeBuilder_ != null) {
        return jokeBuilder_.getMessageOrBuilder();
      } else {
        return joke_ == null ?
            sb.jokesonthego.jokeservice.Joke.getDefaultInstance() : joke_;
      }
    }
    /**
     * <code>.jokeserver.Joke joke = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        sb.jokesonthego.jokeservice.Joke, sb.jokesonthego.jokeservice.Joke.Builder, sb.jokesonthego.jokeservice.JokeOrBuilder> 
        getJokeFieldBuilder() {
      if (jokeBuilder_ == null) {
        jokeBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            sb.jokesonthego.jokeservice.Joke, sb.jokesonthego.jokeservice.Joke.Builder, sb.jokesonthego.jokeservice.JokeOrBuilder>(
                getJoke(),
                getParentForChildren(),
                isClean());
        joke_ = null;
      }
      return jokeBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:jokeserver.GetAnyRandomJokeResponse)
  }

  // @@protoc_insertion_point(class_scope:jokeserver.GetAnyRandomJokeResponse)
  private static final sb.jokesonthego.jokeservice.GetAnyRandomJokeResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new sb.jokesonthego.jokeservice.GetAnyRandomJokeResponse();
  }

  public static sb.jokesonthego.jokeservice.GetAnyRandomJokeResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetAnyRandomJokeResponse>
      PARSER = new com.google.protobuf.AbstractParser<GetAnyRandomJokeResponse>() {
    @java.lang.Override
    public GetAnyRandomJokeResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<GetAnyRandomJokeResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetAnyRandomJokeResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public sb.jokesonthego.jokeservice.GetAnyRandomJokeResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

