// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: protobuf/jokeserver.proto
// Protobuf Java Version: 4.27.1

package sb.jokesonthego.jokeservice;

public interface GetAnyRandomJokeRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:jokeserver.GetAnyRandomJokeRequest)
    com.google.protobuf.MessageOrBuilder {
}
