// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: protobuf/jokeserver.proto
// Protobuf Java Version: 4.27.1

package sb.jokesonthego.jokeservice;

public interface GetAnyRandomJokeResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:jokeserver.GetAnyRandomJokeResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.jokeserver.Joke joke = 1;</code>
   * @return Whether the joke field is set.
   */
  boolean hasJoke();
  /**
   * <code>.jokeserver.Joke joke = 1;</code>
   * @return The joke.
   */
  sb.jokesonthego.jokeservice.Joke getJoke();
  /**
   * <code>.jokeserver.Joke joke = 1;</code>
   */
  sb.jokesonthego.jokeservice.JokeOrBuilder getJokeOrBuilder();
}
