// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: protobuf/jokeserver.proto
// Protobuf Java Version: 4.27.1

package io.github.stephen_bapple.jokesonthegoservice;

/**
 * Protobuf type {@code jokeserver.GetAnyRandomJokeRequest}
 */
public final class GetAnyRandomJokeRequest extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:jokeserver.GetAnyRandomJokeRequest)
    GetAnyRandomJokeRequestOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 1,
      /* suffix= */ "",
      GetAnyRandomJokeRequest.class.getName());
  }
  // Use GetAnyRandomJokeRequest.newBuilder() to construct.
  private GetAnyRandomJokeRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private GetAnyRandomJokeRequest() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.github.stephen_bapple.jokesonthegoservice.JokeServerProto.internal_static_jokeserver_GetAnyRandomJokeRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.github.stephen_bapple.jokesonthegoservice.JokeServerProto.internal_static_jokeserver_GetAnyRandomJokeRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.github.stephen_bapple.jokesonthegoservice.GetAnyRandomJokeRequest.class, io.github.stephen_bapple.jokesonthegoservice.GetAnyRandomJokeRequest.Builder.class);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.github.stephen_bapple.jokesonthegoservice.GetAnyRandomJokeRequest)) {
      return super.equals(obj);
    }
    io.github.stephen_bapple.jokesonthegoservice.GetAnyRandomJokeRequest other = (io.github.stephen_bapple.jokesonthegoservice.GetAnyRandomJokeRequest) obj;

    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.github.stephen_bapple.jokesonthegoservice.GetAnyRandomJokeRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.github.stephen_bapple.jokesonthegoservice.GetAnyRandomJokeRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.github.stephen_bapple.jokesonthegoservice.GetAnyRandomJokeRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.github.stephen_bapple.jokesonthegoservice.GetAnyRandomJokeRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.github.stephen_bapple.jokesonthegoservice.GetAnyRandomJokeRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.github.stephen_bapple.jokesonthegoservice.GetAnyRandomJokeRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.github.stephen_bapple.jokesonthegoservice.GetAnyRandomJokeRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.github.stephen_bapple.jokesonthegoservice.GetAnyRandomJokeRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static io.github.stephen_bapple.jokesonthegoservice.GetAnyRandomJokeRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static io.github.stephen_bapple.jokesonthegoservice.GetAnyRandomJokeRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.github.stephen_bapple.jokesonthegoservice.GetAnyRandomJokeRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.github.stephen_bapple.jokesonthegoservice.GetAnyRandomJokeRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.github.stephen_bapple.jokesonthegoservice.GetAnyRandomJokeRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code jokeserver.GetAnyRandomJokeRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:jokeserver.GetAnyRandomJokeRequest)
      io.github.stephen_bapple.jokesonthegoservice.GetAnyRandomJokeRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.github.stephen_bapple.jokesonthegoservice.JokeServerProto.internal_static_jokeserver_GetAnyRandomJokeRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.github.stephen_bapple.jokesonthegoservice.JokeServerProto.internal_static_jokeserver_GetAnyRandomJokeRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.github.stephen_bapple.jokesonthegoservice.GetAnyRandomJokeRequest.class, io.github.stephen_bapple.jokesonthegoservice.GetAnyRandomJokeRequest.Builder.class);
    }

    // Construct using io.github.stephen_bapple.jokesonthegoservice.GetAnyRandomJokeRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.github.stephen_bapple.jokesonthegoservice.JokeServerProto.internal_static_jokeserver_GetAnyRandomJokeRequest_descriptor;
    }

    @java.lang.Override
    public io.github.stephen_bapple.jokesonthegoservice.GetAnyRandomJokeRequest getDefaultInstanceForType() {
      return io.github.stephen_bapple.jokesonthegoservice.GetAnyRandomJokeRequest.getDefaultInstance();
    }

    @java.lang.Override
    public io.github.stephen_bapple.jokesonthegoservice.GetAnyRandomJokeRequest build() {
      io.github.stephen_bapple.jokesonthegoservice.GetAnyRandomJokeRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.github.stephen_bapple.jokesonthegoservice.GetAnyRandomJokeRequest buildPartial() {
      io.github.stephen_bapple.jokesonthegoservice.GetAnyRandomJokeRequest result = new io.github.stephen_bapple.jokesonthegoservice.GetAnyRandomJokeRequest(this);
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.github.stephen_bapple.jokesonthegoservice.GetAnyRandomJokeRequest) {
        return mergeFrom((io.github.stephen_bapple.jokesonthegoservice.GetAnyRandomJokeRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.github.stephen_bapple.jokesonthegoservice.GetAnyRandomJokeRequest other) {
      if (other == io.github.stephen_bapple.jokesonthegoservice.GetAnyRandomJokeRequest.getDefaultInstance()) return this;
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }

    // @@protoc_insertion_point(builder_scope:jokeserver.GetAnyRandomJokeRequest)
  }

  // @@protoc_insertion_point(class_scope:jokeserver.GetAnyRandomJokeRequest)
  private static final io.github.stephen_bapple.jokesonthegoservice.GetAnyRandomJokeRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.github.stephen_bapple.jokesonthegoservice.GetAnyRandomJokeRequest();
  }

  public static io.github.stephen_bapple.jokesonthegoservice.GetAnyRandomJokeRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetAnyRandomJokeRequest>
      PARSER = new com.google.protobuf.AbstractParser<GetAnyRandomJokeRequest>() {
    @java.lang.Override
    public GetAnyRandomJokeRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<GetAnyRandomJokeRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetAnyRandomJokeRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.github.stephen_bapple.jokesonthegoservice.GetAnyRandomJokeRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

