// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.27.1
// source: protobuf/jokeserver.proto

package joke_service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// JokeServiceClient is the client API for JokeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type JokeServiceClient interface {
	GetAnyRandomJoke(ctx context.Context, in *GetAnyRandomJokeRequest, opts ...grpc.CallOption) (*GetAnyRandomJokeResponse, error)
	GetAnyRandomJoke2Test(ctx context.Context, in *GetAnyRandomJokeRequest, opts ...grpc.CallOption) (*GetAnyRandomJokeResponse, error)
}

type jokeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewJokeServiceClient(cc grpc.ClientConnInterface) JokeServiceClient {
	return &jokeServiceClient{cc}
}

func (c *jokeServiceClient) GetAnyRandomJoke(ctx context.Context, in *GetAnyRandomJokeRequest, opts ...grpc.CallOption) (*GetAnyRandomJokeResponse, error) {
	out := new(GetAnyRandomJokeResponse)
	err := c.cc.Invoke(ctx, "/jokeserver.JokeService/GetAnyRandomJoke", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jokeServiceClient) GetAnyRandomJoke2Test(ctx context.Context, in *GetAnyRandomJokeRequest, opts ...grpc.CallOption) (*GetAnyRandomJokeResponse, error) {
	out := new(GetAnyRandomJokeResponse)
	err := c.cc.Invoke(ctx, "/jokeserver.JokeService/GetAnyRandomJoke2Test", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// JokeServiceServer is the server API for JokeService service.
// All implementations must embed UnimplementedJokeServiceServer
// for forward compatibility
type JokeServiceServer interface {
	GetAnyRandomJoke(context.Context, *GetAnyRandomJokeRequest) (*GetAnyRandomJokeResponse, error)
	GetAnyRandomJoke2Test(context.Context, *GetAnyRandomJokeRequest) (*GetAnyRandomJokeResponse, error)
	mustEmbedUnimplementedJokeServiceServer()
}

// UnimplementedJokeServiceServer must be embedded to have forward compatible implementations.
type UnimplementedJokeServiceServer struct {
}

func (UnimplementedJokeServiceServer) GetAnyRandomJoke(context.Context, *GetAnyRandomJokeRequest) (*GetAnyRandomJokeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAnyRandomJoke not implemented")
}
func (UnimplementedJokeServiceServer) GetAnyRandomJoke2Test(context.Context, *GetAnyRandomJokeRequest) (*GetAnyRandomJokeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAnyRandomJoke2Test not implemented")
}
func (UnimplementedJokeServiceServer) mustEmbedUnimplementedJokeServiceServer() {}

// UnsafeJokeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to JokeServiceServer will
// result in compilation errors.
type UnsafeJokeServiceServer interface {
	mustEmbedUnimplementedJokeServiceServer()
}

func RegisterJokeServiceServer(s grpc.ServiceRegistrar, srv JokeServiceServer) {
	s.RegisterService(&JokeService_ServiceDesc, srv)
}

func _JokeService_GetAnyRandomJoke_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAnyRandomJokeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JokeServiceServer).GetAnyRandomJoke(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/jokeserver.JokeService/GetAnyRandomJoke",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JokeServiceServer).GetAnyRandomJoke(ctx, req.(*GetAnyRandomJokeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JokeService_GetAnyRandomJoke2Test_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAnyRandomJokeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JokeServiceServer).GetAnyRandomJoke2Test(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/jokeserver.JokeService/GetAnyRandomJoke2Test",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JokeServiceServer).GetAnyRandomJoke2Test(ctx, req.(*GetAnyRandomJokeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// JokeService_ServiceDesc is the grpc.ServiceDesc for JokeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var JokeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "jokeserver.JokeService",
	HandlerType: (*JokeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAnyRandomJoke",
			Handler:    _JokeService_GetAnyRandomJoke_Handler,
		},
		{
			MethodName: "GetAnyRandomJoke2Test",
			Handler:    _JokeService_GetAnyRandomJoke2Test_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protobuf/jokeserver.proto",
}
