// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.27.1
// source: protobuf/jokeserver.proto

package joke_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetAnyRandomJokeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetAnyRandomJokeRequest) Reset() {
	*x = GetAnyRandomJokeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_jokeserver_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAnyRandomJokeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAnyRandomJokeRequest) ProtoMessage() {}

func (x *GetAnyRandomJokeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_jokeserver_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAnyRandomJokeRequest.ProtoReflect.Descriptor instead.
func (*GetAnyRandomJokeRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_jokeserver_proto_rawDescGZIP(), []int{0}
}

type GetAnyRandomJokeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Joke *Joke `protobuf:"bytes,1,opt,name=joke,proto3" json:"joke,omitempty"`
}

func (x *GetAnyRandomJokeResponse) Reset() {
	*x = GetAnyRandomJokeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_jokeserver_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAnyRandomJokeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAnyRandomJokeResponse) ProtoMessage() {}

func (x *GetAnyRandomJokeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_jokeserver_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAnyRandomJokeResponse.ProtoReflect.Descriptor instead.
func (*GetAnyRandomJokeResponse) Descriptor() ([]byte, []int) {
	return file_protobuf_jokeserver_proto_rawDescGZIP(), []int{1}
}

func (x *GetAnyRandomJokeResponse) GetJoke() *Joke {
	if x != nil {
		return x.Joke
	}
	return nil
}

type Joke struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Setup     string `protobuf:"bytes,1,opt,name=setup,proto3" json:"setup,omitempty"`
	Punchline string `protobuf:"bytes,2,opt,name=punchline,proto3" json:"punchline,omitempty"`
}

func (x *Joke) Reset() {
	*x = Joke{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_jokeserver_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Joke) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Joke) ProtoMessage() {}

func (x *Joke) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_jokeserver_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Joke.ProtoReflect.Descriptor instead.
func (*Joke) Descriptor() ([]byte, []int) {
	return file_protobuf_jokeserver_proto_rawDescGZIP(), []int{2}
}

func (x *Joke) GetSetup() string {
	if x != nil {
		return x.Setup
	}
	return ""
}

func (x *Joke) GetPunchline() string {
	if x != nil {
		return x.Punchline
	}
	return ""
}

var File_protobuf_jokeserver_proto protoreflect.FileDescriptor

var file_protobuf_jokeserver_proto_rawDesc = []byte{
	0x0a, 0x19, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x6a, 0x6f, 0x6b, 0x65, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x6a, 0x6f, 0x6b,
	0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x22, 0x19, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x41, 0x6e,
	0x79, 0x52, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x4a, 0x6f, 0x6b, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x22, 0x40, 0x0a, 0x18, 0x47, 0x65, 0x74, 0x41, 0x6e, 0x79, 0x52, 0x61, 0x6e, 0x64,
	0x6f, 0x6d, 0x4a, 0x6f, 0x6b, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x24,
	0x0a, 0x04, 0x6a, 0x6f, 0x6b, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6a,
	0x6f, 0x6b, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x4a, 0x6f, 0x6b, 0x65, 0x52, 0x04,
	0x6a, 0x6f, 0x6b, 0x65, 0x22, 0x3a, 0x0a, 0x04, 0x4a, 0x6f, 0x6b, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x73, 0x65, 0x74, 0x75, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x65, 0x74,
	0x75, 0x70, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x75, 0x6e, 0x63, 0x68, 0x6c, 0x69, 0x6e, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x75, 0x6e, 0x63, 0x68, 0x6c, 0x69, 0x6e, 0x65,
	0x32, 0x6e, 0x0a, 0x0b, 0x4a, 0x6f, 0x6b, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x5f, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x41, 0x6e, 0x79, 0x52, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x4a,
	0x6f, 0x6b, 0x65, 0x12, 0x23, 0x2e, 0x6a, 0x6f, 0x6b, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x2e, 0x47, 0x65, 0x74, 0x41, 0x6e, 0x79, 0x52, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x4a, 0x6f, 0x6b,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x6a, 0x6f, 0x6b, 0x65, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6e, 0x79, 0x52, 0x61, 0x6e, 0x64,
	0x6f, 0x6d, 0x4a, 0x6f, 0x6b, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x42, 0x84, 0x01, 0x0a, 0x2b, 0x69, 0x6f, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x73,
	0x74, 0x65, 0x70, 0x68, 0x65, 0x6e, 0x62, 0x61, 0x70, 0x70, 0x6c, 0x65, 0x2e, 0x6a, 0x6f, 0x6b,
	0x65, 0x73, 0x6f, 0x6e, 0x74, 0x68, 0x65, 0x67, 0x6f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x42, 0x0f, 0x4a, 0x6f, 0x6b, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x74,
	0x6f, 0x50, 0x01, 0x5a, 0x42, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x73, 0x74, 0x65, 0x70, 0x68, 0x65, 0x6e, 0x2d, 0x62, 0x61, 0x70, 0x70, 0x6c, 0x65, 0x2f, 0x6a,
	0x6f, 0x6b, 0x65, 0x73, 0x2d, 0x6f, 0x6e, 0x2d, 0x74, 0x68, 0x65, 0x2d, 0x67, 0x6f, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x67, 0x6f, 0x2f, 0x6a, 0x6f, 0x6b, 0x65, 0x2d,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protobuf_jokeserver_proto_rawDescOnce sync.Once
	file_protobuf_jokeserver_proto_rawDescData = file_protobuf_jokeserver_proto_rawDesc
)

func file_protobuf_jokeserver_proto_rawDescGZIP() []byte {
	file_protobuf_jokeserver_proto_rawDescOnce.Do(func() {
		file_protobuf_jokeserver_proto_rawDescData = protoimpl.X.CompressGZIP(file_protobuf_jokeserver_proto_rawDescData)
	})
	return file_protobuf_jokeserver_proto_rawDescData
}

var file_protobuf_jokeserver_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_protobuf_jokeserver_proto_goTypes = []interface{}{
	(*GetAnyRandomJokeRequest)(nil),  // 0: jokeserver.GetAnyRandomJokeRequest
	(*GetAnyRandomJokeResponse)(nil), // 1: jokeserver.GetAnyRandomJokeResponse
	(*Joke)(nil),                     // 2: jokeserver.Joke
}
var file_protobuf_jokeserver_proto_depIdxs = []int32{
	2, // 0: jokeserver.GetAnyRandomJokeResponse.joke:type_name -> jokeserver.Joke
	0, // 1: jokeserver.JokeService.GetAnyRandomJoke:input_type -> jokeserver.GetAnyRandomJokeRequest
	1, // 2: jokeserver.JokeService.GetAnyRandomJoke:output_type -> jokeserver.GetAnyRandomJokeResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_protobuf_jokeserver_proto_init() }
func file_protobuf_jokeserver_proto_init() {
	if File_protobuf_jokeserver_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protobuf_jokeserver_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAnyRandomJokeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_jokeserver_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAnyRandomJokeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_jokeserver_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Joke); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protobuf_jokeserver_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protobuf_jokeserver_proto_goTypes,
		DependencyIndexes: file_protobuf_jokeserver_proto_depIdxs,
		MessageInfos:      file_protobuf_jokeserver_proto_msgTypes,
	}.Build()
	File_protobuf_jokeserver_proto = out.File
	file_protobuf_jokeserver_proto_rawDesc = nil
	file_protobuf_jokeserver_proto_goTypes = nil
	file_protobuf_jokeserver_proto_depIdxs = nil
}
