// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: protobuf/jokeserver.proto
// Protobuf Java Version: 4.27.1

package io.github.stephenbapple.jokesonthegoservice;

/**
 * Protobuf type {@code jokeserver.Joke}
 */
public final class Joke extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:jokeserver.Joke)
    JokeOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 1,
      /* suffix= */ "",
      Joke.class.getName());
  }
  // Use Joke.newBuilder() to construct.
  private Joke(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private Joke() {
    setup_ = "";
    punchline_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.github.stephenbapple.jokesonthegoservice.JokeServerProto.internal_static_jokeserver_Joke_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.github.stephenbapple.jokesonthegoservice.JokeServerProto.internal_static_jokeserver_Joke_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.github.stephenbapple.jokesonthegoservice.Joke.class, io.github.stephenbapple.jokesonthegoservice.Joke.Builder.class);
  }

  public static final int SETUP_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object setup_ = "";
  /**
   * <code>string setup = 1;</code>
   * @return The setup.
   */
  @java.lang.Override
  public java.lang.String getSetup() {
    java.lang.Object ref = setup_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      setup_ = s;
      return s;
    }
  }
  /**
   * <code>string setup = 1;</code>
   * @return The bytes for setup.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSetupBytes() {
    java.lang.Object ref = setup_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      setup_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PUNCHLINE_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object punchline_ = "";
  /**
   * <code>string punchline = 2;</code>
   * @return The punchline.
   */
  @java.lang.Override
  public java.lang.String getPunchline() {
    java.lang.Object ref = punchline_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      punchline_ = s;
      return s;
    }
  }
  /**
   * <code>string punchline = 2;</code>
   * @return The bytes for punchline.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPunchlineBytes() {
    java.lang.Object ref = punchline_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      punchline_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(setup_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, setup_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(punchline_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, punchline_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(setup_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, setup_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(punchline_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, punchline_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.github.stephenbapple.jokesonthegoservice.Joke)) {
      return super.equals(obj);
    }
    io.github.stephenbapple.jokesonthegoservice.Joke other = (io.github.stephenbapple.jokesonthegoservice.Joke) obj;

    if (!getSetup()
        .equals(other.getSetup())) return false;
    if (!getPunchline()
        .equals(other.getPunchline())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SETUP_FIELD_NUMBER;
    hash = (53 * hash) + getSetup().hashCode();
    hash = (37 * hash) + PUNCHLINE_FIELD_NUMBER;
    hash = (53 * hash) + getPunchline().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.github.stephenbapple.jokesonthegoservice.Joke parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.github.stephenbapple.jokesonthegoservice.Joke parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.github.stephenbapple.jokesonthegoservice.Joke parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.github.stephenbapple.jokesonthegoservice.Joke parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.github.stephenbapple.jokesonthegoservice.Joke parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.github.stephenbapple.jokesonthegoservice.Joke parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.github.stephenbapple.jokesonthegoservice.Joke parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.github.stephenbapple.jokesonthegoservice.Joke parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static io.github.stephenbapple.jokesonthegoservice.Joke parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static io.github.stephenbapple.jokesonthegoservice.Joke parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.github.stephenbapple.jokesonthegoservice.Joke parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.github.stephenbapple.jokesonthegoservice.Joke parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.github.stephenbapple.jokesonthegoservice.Joke prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code jokeserver.Joke}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:jokeserver.Joke)
      io.github.stephenbapple.jokesonthegoservice.JokeOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.github.stephenbapple.jokesonthegoservice.JokeServerProto.internal_static_jokeserver_Joke_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.github.stephenbapple.jokesonthegoservice.JokeServerProto.internal_static_jokeserver_Joke_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.github.stephenbapple.jokesonthegoservice.Joke.class, io.github.stephenbapple.jokesonthegoservice.Joke.Builder.class);
    }

    // Construct using io.github.stephenbapple.jokesonthegoservice.Joke.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      setup_ = "";
      punchline_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.github.stephenbapple.jokesonthegoservice.JokeServerProto.internal_static_jokeserver_Joke_descriptor;
    }

    @java.lang.Override
    public io.github.stephenbapple.jokesonthegoservice.Joke getDefaultInstanceForType() {
      return io.github.stephenbapple.jokesonthegoservice.Joke.getDefaultInstance();
    }

    @java.lang.Override
    public io.github.stephenbapple.jokesonthegoservice.Joke build() {
      io.github.stephenbapple.jokesonthegoservice.Joke result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.github.stephenbapple.jokesonthegoservice.Joke buildPartial() {
      io.github.stephenbapple.jokesonthegoservice.Joke result = new io.github.stephenbapple.jokesonthegoservice.Joke(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(io.github.stephenbapple.jokesonthegoservice.Joke result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.setup_ = setup_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.punchline_ = punchline_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.github.stephenbapple.jokesonthegoservice.Joke) {
        return mergeFrom((io.github.stephenbapple.jokesonthegoservice.Joke)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.github.stephenbapple.jokesonthegoservice.Joke other) {
      if (other == io.github.stephenbapple.jokesonthegoservice.Joke.getDefaultInstance()) return this;
      if (!other.getSetup().isEmpty()) {
        setup_ = other.setup_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getPunchline().isEmpty()) {
        punchline_ = other.punchline_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              setup_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              punchline_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object setup_ = "";
    /**
     * <code>string setup = 1;</code>
     * @return The setup.
     */
    public java.lang.String getSetup() {
      java.lang.Object ref = setup_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        setup_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string setup = 1;</code>
     * @return The bytes for setup.
     */
    public com.google.protobuf.ByteString
        getSetupBytes() {
      java.lang.Object ref = setup_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        setup_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string setup = 1;</code>
     * @param value The setup to set.
     * @return This builder for chaining.
     */
    public Builder setSetup(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      setup_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string setup = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearSetup() {
      setup_ = getDefaultInstance().getSetup();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string setup = 1;</code>
     * @param value The bytes for setup to set.
     * @return This builder for chaining.
     */
    public Builder setSetupBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      setup_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object punchline_ = "";
    /**
     * <code>string punchline = 2;</code>
     * @return The punchline.
     */
    public java.lang.String getPunchline() {
      java.lang.Object ref = punchline_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        punchline_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string punchline = 2;</code>
     * @return The bytes for punchline.
     */
    public com.google.protobuf.ByteString
        getPunchlineBytes() {
      java.lang.Object ref = punchline_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        punchline_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string punchline = 2;</code>
     * @param value The punchline to set.
     * @return This builder for chaining.
     */
    public Builder setPunchline(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      punchline_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string punchline = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearPunchline() {
      punchline_ = getDefaultInstance().getPunchline();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string punchline = 2;</code>
     * @param value The bytes for punchline to set.
     * @return This builder for chaining.
     */
    public Builder setPunchlineBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      punchline_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:jokeserver.Joke)
  }

  // @@protoc_insertion_point(class_scope:jokeserver.Joke)
  private static final io.github.stephenbapple.jokesonthegoservice.Joke DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.github.stephenbapple.jokesonthegoservice.Joke();
  }

  public static io.github.stephenbapple.jokesonthegoservice.Joke getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Joke>
      PARSER = new com.google.protobuf.AbstractParser<Joke>() {
    @java.lang.Override
    public Joke parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Joke> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Joke> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.github.stephenbapple.jokesonthegoservice.Joke getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

