// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: protobuf/jokeserver.proto
// Protobuf Java Version: 4.27.1

package io.github.stephenbapple.jokesonthegoservice;

public interface JokeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:jokeserver.Joke)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string setup = 1;</code>
   * @return The setup.
   */
  java.lang.String getSetup();
  /**
   * <code>string setup = 1;</code>
   * @return The bytes for setup.
   */
  com.google.protobuf.ByteString
      getSetupBytes();

  /**
   * <code>string punchline = 2;</code>
   * @return The punchline.
   */
  java.lang.String getPunchline();
  /**
   * <code>string punchline = 2;</code>
   * @return The bytes for punchline.
   */
  com.google.protobuf.ByteString
      getPunchlineBytes();
}
