// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: protobuf/jokeserver.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package sb.jokesonthego.jokeservice;

@kotlin.jvm.JvmName("-initializegetAnyRandomJokeRequest")
public inline fun getAnyRandomJokeRequest(block: sb.jokesonthego.jokeservice.GetAnyRandomJokeRequestKt.Dsl.() -> kotlin.Unit): sb.jokesonthego.jokeservice.GetAnyRandomJokeRequest =
  sb.jokesonthego.jokeservice.GetAnyRandomJokeRequestKt.Dsl._create(sb.jokesonthego.jokeservice.GetAnyRandomJokeRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `jokeserver.GetAnyRandomJokeRequest`
 */
public object GetAnyRandomJokeRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: sb.jokesonthego.jokeservice.GetAnyRandomJokeRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: sb.jokesonthego.jokeservice.GetAnyRandomJokeRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): sb.jokesonthego.jokeservice.GetAnyRandomJokeRequest = _builder.build()
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun sb.jokesonthego.jokeservice.GetAnyRandomJokeRequest.copy(block: `sb.jokesonthego.jokeservice`.GetAnyRandomJokeRequestKt.Dsl.() -> kotlin.Unit): sb.jokesonthego.jokeservice.GetAnyRandomJokeRequest =
  `sb.jokesonthego.jokeservice`.GetAnyRandomJokeRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

