// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: protobuf/jokeserver.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package sb.jokesonthego.jokeservice;

@kotlin.jvm.JvmName("-initializegetAnyRandomJokeResponse")
public inline fun getAnyRandomJokeResponse(block: sb.jokesonthego.jokeservice.GetAnyRandomJokeResponseKt.Dsl.() -> kotlin.Unit): sb.jokesonthego.jokeservice.GetAnyRandomJokeResponse =
  sb.jokesonthego.jokeservice.GetAnyRandomJokeResponseKt.Dsl._create(sb.jokesonthego.jokeservice.GetAnyRandomJokeResponse.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `jokeserver.GetAnyRandomJokeResponse`
 */
public object GetAnyRandomJokeResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: sb.jokesonthego.jokeservice.GetAnyRandomJokeResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: sb.jokesonthego.jokeservice.GetAnyRandomJokeResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): sb.jokesonthego.jokeservice.GetAnyRandomJokeResponse = _builder.build()

    /**
     * `.jokeserver.Joke joke = 1;`
     */
    public var joke: sb.jokesonthego.jokeservice.Joke
      @JvmName("getJoke")
      get() = _builder.getJoke()
      @JvmName("setJoke")
      set(value) {
        _builder.setJoke(value)
      }
    /**
     * `.jokeserver.Joke joke = 1;`
     */
    public fun clearJoke() {
      _builder.clearJoke()
    }
    /**
     * `.jokeserver.Joke joke = 1;`
     * @return Whether the joke field is set.
     */
    public fun hasJoke(): kotlin.Boolean {
      return _builder.hasJoke()
    }
    public val GetAnyRandomJokeResponseKt.Dsl.jokeOrNull: sb.jokesonthego.jokeservice.Joke?
      get() = _builder.jokeOrNull
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun sb.jokesonthego.jokeservice.GetAnyRandomJokeResponse.copy(block: `sb.jokesonthego.jokeservice`.GetAnyRandomJokeResponseKt.Dsl.() -> kotlin.Unit): sb.jokesonthego.jokeservice.GetAnyRandomJokeResponse =
  `sb.jokesonthego.jokeservice`.GetAnyRandomJokeResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val sb.jokesonthego.jokeservice.GetAnyRandomJokeResponseOrBuilder.jokeOrNull: sb.jokesonthego.jokeservice.Joke?
  get() = if (hasJoke()) getJoke() else null

