// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: protobuf/jokeserver.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package sb.jokesonthego.jokeservice;

@kotlin.jvm.JvmName("-initializejoke")
public inline fun joke(block: sb.jokesonthego.jokeservice.JokeKt.Dsl.() -> kotlin.Unit): sb.jokesonthego.jokeservice.Joke =
  sb.jokesonthego.jokeservice.JokeKt.Dsl._create(sb.jokesonthego.jokeservice.Joke.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `jokeserver.Joke`
 */
public object JokeKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: sb.jokesonthego.jokeservice.Joke.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: sb.jokesonthego.jokeservice.Joke.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): sb.jokesonthego.jokeservice.Joke = _builder.build()

    /**
     * `string setup = 1;`
     */
    public var setup: kotlin.String
      @JvmName("getSetup")
      get() = _builder.getSetup()
      @JvmName("setSetup")
      set(value) {
        _builder.setSetup(value)
      }
    /**
     * `string setup = 1;`
     */
    public fun clearSetup() {
      _builder.clearSetup()
    }

    /**
     * `string punchline = 2;`
     */
    public var punchline: kotlin.String
      @JvmName("getPunchline")
      get() = _builder.getPunchline()
      @JvmName("setPunchline")
      set(value) {
        _builder.setPunchline(value)
      }
    /**
     * `string punchline = 2;`
     */
    public fun clearPunchline() {
      _builder.clearPunchline()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun sb.jokesonthego.jokeservice.Joke.copy(block: `sb.jokesonthego.jokeservice`.JokeKt.Dsl.() -> kotlin.Unit): sb.jokesonthego.jokeservice.Joke =
  `sb.jokesonthego.jokeservice`.JokeKt.Dsl._create(this.toBuilder()).apply { block() }._build()

