name: Release Kotlin Protobuf stubs

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
            sparse-checkout: protobuf/kotlin
            sparse-checkout-cone-mode: false

      # Thanks to danial-k https://github.com/actions/checkout/issues/1430#issuecomment-1756326892
      - name: Move mobile app files to root
        run: |
          ls -lah
          shopt -s dotglob
          mv protobuf/kotlin/* .
          rm -rf protobuf
          ls -lah
 
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      - name: Build with Gradle
        run: ./gradlew build

      - name: Publish to GitHub Packages
        run: ./gradlew publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_USERNAME: ${{ secrets.GITHUB_USERNAME }}
